name: Android Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置JDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 编译Debug版本APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: 上传APK到Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DeskPet-APK
          path: app/build/outputs/apk/debug/app-debug.apk

