name: Android Build APK
on:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目全部代码
        uses: actions/checkout@v4

      - name: 配置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 安装系统Gradle
        run: sudo apt update && sudo apt install gradle -y

      - name: 编译Debug APK
        run: gradle assembleDebug

      - name: 导出APK安装包
        uses: actions/upload-artifact@v4
        with:
          name: DeskPet-APK压缩包
          path: app/build/outputs/apk/debug/*.apk

